language: ruby
cache: bundler
rvm: 2.5
before_script:
  - "bundle exec rails server -p 3000 -d"
  - "kill -9 $(cat tmp/pids/server.pid)"
deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key:
      secure: "$SECRETACCESSKEY"
    region: us-east-1
    app: MITMunc
    env: Mitmunc-test-env
    bucket_name: elasticbeanstalk-us-east-1-296292345586
    on:
      repo: MITMUNC/mitmunc-website
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
  - provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key:
      secure: "$SECRETACCESSKEY"
    region: us-east-1
    app: MITMunc
    env: Mitmunc-env
    bucket_name: elasticbeanstalk-us-east-1-296292345586
    on:
      repo: MITMUNC/mitmunc-website
      branch: master
